# Generated by Django 6.0.5 on 2026-05-30 17:48

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=apps.files.models.uploaded_file_path),
        ),
    ]
